name: third-workflow
on : workflow_dispatch
jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: say your name
        run: echo "my name is keshav lichade"
      - name: say your profession
        run: echo "I am a Devops engineer"
